"""empty message

Revision ID: 3a6b5a520aed
Revises:
Create Date: 2024-02-16 01:36:40.075128

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a6b5a520aed"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_users")
    # ### end Alembic commands ###
